global:
  scrape_interval: 5s

scrape_configs:
  # Scrape самого Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # Scrape Postgres Exporter (master)
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']

  # Scrape Postgres Exporter (replica)
  - job_name: 'postgres_replica_exporter'
    static_configs:
      - targets: ['postgres_replica_exporter:9187']
   
  - job_name: 'kafka-exporter'
    static_configs:
      # Имя сервиса:порт = kafka_exporter:9308 внутри docker-сети
      - targets: ['kafka_exporter:9308']

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis_exporter:9121']

  - job_name: 'aspnetcore_app'
    static_configs:
      - targets: ['host.docker.internal:8080']