services:
  # --- [POSTGRES MASTER] ---
  postgres_master:
    container_name: webapi-postgres-master
    image: postgres:17
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: example_db
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: always
    volumes:
      - postgres_master_data:/var/lib/postgresql/data
      - ./init-master.sh:/docker-entrypoint-initdb.d/init-master.sh
      - ./init-master.sql:/docker-entrypoint-initdb.d/init-master.sql

  # --- [POSTGRES REPLICA] ---
  postgres_replica:
    container_name: webapi-postgres-replica
    image: postgres:17
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: example_db
    depends_on:
      - postgres_master
    ports:
      - "5433:5432"
    networks:
      - app-network
    restart: always
    volumes:
      - postgres_replica_data:/var/lib/postgresql/data
      - ./init-replica.sh:/docker-entrypoint-initdb.d/init-replica.sh
      - ./init-replica.sql:/docker-entrypoint-initdb.d/init-replica.sql

  # --- [ZOOKEEPER] ---
  zookeeper:
    container_name: webapi-zookeeper
    image: wurstmeister/zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - app-network
    restart: always

  # --- [KAFKA] ---
  kafka:
    container_name: webapi-kafka
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper
    networks:
      - app-network
    restart: always

  # --- [REDIS] ---
  redis:
    container_name: webapi-redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network
    restart: always

volumes:
  postgres_master_data:
  postgres_replica_data:

networks:
  app-network:
    driver: bridge